const ADD_TODO = "ADD_TODO";
const VIEW_ALL = "VIEW_ALL";
const VIEW_COMPLETED = "VIEW_COMPLETED";
const DELETE_TODO = "DELETE_TODO";
const UPDATE_TODO = "UPDATE_TODO";

export {
	ADD_TODO,
	VIEW_ALL,
	VIEW_COMPLETED,
	DELETE_TODO,
	UPDATE_TODO
};
